config/routes.rb
Guide::Application.routes.draw do
  resources :guide_items
  resources :questions

  get "home/index"
  get 'tags/:tag', to:'guide_items#index', as: :tag

  root :to => 'guide_items#index'
end

app/models/guide_item.rb
class GuideItem < ActiveRecord::Base
  attr_accessible :author, :title, :tag_list
  acts_as_taggable

  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guide_items_controller.rb
class GuideItemsController < ApplicationController
  # GET /guide_items
  # GET /guide_items.json
  def index
    if params[:tag]
      @guide_items = GuideItem.tagged_with(params[:tag])
    else
      @guide_items = GuideItem.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guide_items }
    end
  end

  # GET /guide_items/1
  # GET /guide_items/1.json
  def show
    @guide_item = GuideItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guide_item }
    end
  end

  # GET /guide_items/new
  # GET /guide_items/new.json
  def new
    @guide_item = GuideItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guide_item }
    end
  end

  # GET /guide_items/1/edit
  def edit
    @guide_item = GuideItem.find(params[:id])
  end

  # POST /guide_items
  # POST /guide_items.json
  def create
    @guide_item = GuideItem.new(params[:guide_item])

    respond_to do |format|
      if @guide_item.save
        format.html { redirect_to @guide_item, notice: 'Guide item was successfully created.' }
        format.json { render json: @guide_item, status: :created, location: @guide_item }
      else
        format.html { render action: "new" }
        format.json { render json: @guide_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guide_items/1
  # PUT /guide_items/1.json
  def update
    @guide_item = GuideItem.find(params[:id])

    respond_to do |format|
      if @guide_item.update_attributes(params[:guide_item])
        format.html { redirect_to @guide_item, notice: 'Guide item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guide_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guide_items/1
  # DELETE /guide_items/1.json
  def destroy
    @guide_item = GuideItem.find(params[:id])
    @guide_item.destroy

    respond_to do |format|
      format.html { redirect_to guide_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  respond_to :html

  def index
    @questions = Question.all
    respond_with @questions
  end

  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to question_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guide_items_helper.rb
module GuideItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/guide_items/_form.html.erb
<%= form_for(@guide_item) do |f| %>
  <% if @guide_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide_item.errors.count, "error") %> prohibited this guide_item from being saved:</h2>

      <ul>
      <% @guide_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guide_items/edit.html.erb
<h1>Editing guide_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide_item %> |
<%= link_to 'Back', :back %>

app/views/guide_items/index.html.erb
<center><h1>Guides</h1></center>

<%= link_to new_guide_item_path, class:"btn" do %>
  <i class="icon-plus"></i> New guide
<% end %>

<br/>
<br/>
<br/>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guide_items.each do |guide_item| %>
  <tr>
    <td><%= guide_item.title %></td>
    <td><%= guide_item.author %></td>
    <td><%= raw guide_item.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></td>
    <td><%= link_to 'Show', guide_item %></td>
    <td><%= link_to 'Edit', edit_guide_item_path(guide_item) %></td>
    <td><%= link_to 'Destroy', guide_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<ul class="tags">
  <% tag_cloud GuideItem.tag_counts, %w[s m l] do |tag, css_class| %>
    <li><%= link_to tag.name, tag_path(tag.name), class: css_class %></li>
  <% end %>
  <li><a href="">+</a></li>
</ul>

app/views/guide_items/new.html.erb
<h1>New guide item</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/guide_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @guide_item.title %>
</p>

<p>
  <b>Author:</b>
  <%= @guide_item.author %>
</p>


<%= link_to 'Edit', edit_guide_item_path(@guide_item) %> |
<%= link_to 'Back', guide_items_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="#">Guides</a>

      <div class="nav-collapse collapse">

        <ul class="nav pull-right">
          <li>
            <form class="navbar-search" action="">
              <input type="text" class="search-query span2" placeholder="Search">
            </form>
          </li>
          <li class="divider-vertical"></li>
          <li><a href="#">Sign in</a></li>
        </ul>

      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guide</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing guide_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide_item %> |
<%= link_to 'Back', :back %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.description %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question item', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @question.description %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', :back %>